# TRAVEL & TOURISM ANALYSIS

## Import Libraries

In [2]:
import pandas as pd
import numpy as np

## Load Data

In [3]:
df=pd.read_csv(r"Data\H1(infotact).csv")
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,DepositType,Agent,Company,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,No Deposit,NULL,NULL,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,No Deposit,NULL,NULL,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,No Deposit,NULL,NULL,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,No Deposit,304,NULL,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,No Deposit,240,NULL,0,Transient,98.0,0,1,Check-Out,2015-07-03

## Dataset Overview

In [4]:
df.shape

(40060, 31)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40060 entries, 0 to 40059
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   40060 non-null  int64
 1   LeadTime                     40060 non-null  int64
 2   ArrivalDateYear              40060 non-null  int64
 3   ArrivalDateMonth             40060 non-null  object
 4   ArrivalDateWeekNumber        40060 non-null  int64
 5   ArrivalDateDayOfMonth        40060 non-null  int64
 6   StaysInWeekendNights         40060 non-null  int64
 7   StaysInWeekNights            40060 non-null  int64
 8   Adults                       40060 non-null  int64
 9   Children                     40060 non-null  int64
 10  Babies                       40060 non-null  int64
 11  Meal                         40060 non-null  object
 12  Country                      39596 non-null  object
 13  MarketSegment                40060 non-null  object
 14  DistributionChannel          40060 non-null  object
 15  IsRepeatedGuest              40060 non-null  int64
 16  PreviousCancellations        40060 non-null  int64
 17  PreviousBookingsNotCanceled  40060 non-null  int64
 18  ReservedRoomType             40060 non-null  object
 19  AssignedRoomType             40060 non-null  object
 20  BookingChanges               40060 non-null  int64
 21  DepositType                  40060 non-null  object
 22  Agent                        40060 non-null  object
 23  Company                      40060 non-null  object
 24  DaysInWaitingList            40060 non-null  int64
 25  CustomerType                 40060 non-null  object
 26  ADR                          40060 non-null  float64
 27  RequiredCarParkingSpaces     40060 non-null  int64
 28  TotalOfSpecialRequests       40060 non-null  int64
 29  ReservationStatus            40060 non-null  object
 30  ReservationStatusDate        40060 non-null  object
dtypes: float64(1), int64(17), object(13)
memory usage: 9.5+ MB

## Checking Duplicates

In [6]:
df.duplicated().sum()

np.int64(6092)

## Removing Duplicates

In [7]:
df.drop_duplicates(inplace=True)

### Rechecking the dataset shape

In [8]:
df.shape

(33968, 31)

## Checking Missing values

In [9]:
df.isnull().sum()

IsCanceled                       0
LeadTime                         0
ArrivalDateYear                  0
ArrivalDateMonth                 0
ArrivalDateWeekNumber            0
ArrivalDateDayOfMonth            0
StaysInWeekendNights             0
StaysInWeekNights                0
Adults                           0
Children                         0
Babies                           0
Meal                             0
Country                        446
MarketSegment                    0
DistributionChannel              0
IsRepeatedGuest                  0
PreviousCancellations            0
PreviousBookingsNotCanceled      0
ReservedRoomType                 0
AssignedRoomType                 0
BookingChanges                   0
DepositType                      0
Agent                            0
Company                          0
DaysInWaitingList                0
CustomerType                     0
ADR                              0
RequiredCarParkingSpaces         0
TotalOfSpecialRequests           0
ReservationStatus                0
ReservationStatusDate            0
dtype: int64

### Agent and Company contains majority null data(string),so drop

In [10]:
df.drop(['Agent','Company'],axis=1,inplace=True)

In [11]:
df

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,AssignedRoomType,BookingChanges,DepositType,DaysInWaitingList,CustomerType,ADR,RequiredCarParkingSpaces,TotalOfSpecialRequests,ReservationStatus,ReservationStatusDate
0,0,342,2015,July,27,1,0,0,2,0,...,C,3,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,0,737,2015,July,27,1,0,0,2,0,...,C,4,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,0,7,2015,July,27,1,0,1,1,0,...,C,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,0,13,2015,July,27,1,0,1,1,0,...,A,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,0,14,2015,July,27,1,0,2,2,0,...,A,0,No Deposit,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40055,0,212,2017,August,35,31,2,8,2,1,...,A,1,No Deposit,0,Transient,89.75,0,0,Check-Out,2017-09-10
40056,0,169,2017,August,35,30,2,9,2,0,...,E,0,No Deposit,0,Transient-Party,202.27,0,1,Check-Out,2017-09-10
40057,0,204,2017,August,35,29,4,10,2,0,...,E,0,No Deposit,0,Transient,153.57,0,3,Check-Out,2017-09-12
40058,0,211,2017,August,35,31,4,10,2,0,...,D,0,No Deposit,0,Contract,112.80,0,1,Check-Out,2017-09-14
40059,0,161,2017,August,35,31,4,10,2,0,...,A,0,No Deposit,0,Transient,99.06,0,0,Check-Out,2017-09-14

### filling missing values with unknown

In [12]:
df['Country']=df['Country'].fillna('Unknown')

#### rechecking any other missing values

In [13]:
df.isnull().sum()

IsCanceled                     0
LeadTime                       0
ArrivalDateYear                0
ArrivalDateMonth               0
ArrivalDateWeekNumber          0
ArrivalDateDayOfMonth          0
StaysInWeekendNights           0
StaysInWeekNights              0
Adults                         0
Children                       0
Babies                         0
Meal                           0
Country                        0
MarketSegment                  0
DistributionChannel            0
IsRepeatedGuest                0
PreviousCancellations          0
PreviousBookingsNotCanceled    0
ReservedRoomType               0
AssignedRoomType               0
BookingChanges                 0
DepositType                    0
DaysInWaitingList              0
CustomerType                   0
ADR                            0
RequiredCarParkingSpaces       0
TotalOfSpecialRequests         0
ReservationStatus              0
ReservationStatusDate          0
dtype: int64

### Adding new features

In [14]:
df['Total Guest']=df['Children'] + df['Adults'] + df['Babies']

In [15]:
df['HasChildren']=(df['Children']>0).astype(int)

In [16]:
df['HasBabies']=(df['Babies']>0).astype(int)

In [17]:
df['Total Stay Duration']=df['StaysInWeekendNights'] + df['StaysInWeekNights']

In [18]:
df['Revenue']=df['ADR'] * df['Total Stay Duration']

In [19]:
df['TotalPreviousBookings']=df['PreviousCancellations'] + df['PreviousBookingsNotCanceled']

In [20]:
df['CancellationRate']=df['PreviousCancellations'] / (df['TotalPreviousBookings'] + 1)

In [21]:
df['BookingChangeRate']=df['BookingChanges'] / (df['LeadTime'] + 1)

### Saving cleaned & features added Dataset to a new csv file

In [22]:
df.to_csv(r'Data\H1_cleaned_feature_engineering.csv')

In [23]:
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,ReservationStatus,ReservationStatusDate,Total Guest,HasChildren,HasBabies,Total Stay Duration,Revenue,TotalPreviousBookings,CancellationRate,BookingChangeRate
0,0,342,2015,July,27,1,0,0,2,0,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.008746
1,0,737,2015,July,27,1,0,0,2,0,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.005420
2,0,7,2015,July,27,1,0,1,1,0,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
3,0,13,2015,July,27,1,0,1,1,0,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
4,0,14,2015,July,27,1,0,2,2,0,...,Check-Out,2015-07-03,2,0,0,2,196.0,0,0.0,0.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33968 entries, 0 to 40059
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   IsCanceled                   33968 non-null  int64
 1   LeadTime                     33968 non-null  int64
 2   ArrivalDateYear              33968 non-null  int64
 3   ArrivalDateMonth             33968 non-null  object
 4   ArrivalDateWeekNumber        33968 non-null  int64
 5   ArrivalDateDayOfMonth        33968 non-null  int64
 6   StaysInWeekendNights         33968 non-null  int64
 7   StaysInWeekNights            33968 non-null  int64
 8   Adults                       33968 non-null  int64
 9   Children                     33968 non-null  int64
 10  Babies                       33968 non-null  int64
 11  Meal                         33968 non-null  object
 12  Country                      33968 non-null  object
 13  MarketSegment                33968 non-null  object
 14  DistributionChannel          33968 non-null  object
 15  IsRepeatedGuest              33968 non-null  int64
 16  PreviousCancellations        33968 non-null  int64
 17  PreviousBookingsNotCanceled  33968 non-null  int64
 18  ReservedRoomType             33968 non-null  object
 19  AssignedRoomType             33968 non-null  object
 20  BookingChanges               33968 non-null  int64
 21  DepositType                  33968 non-null  object
 22  DaysInWaitingList            33968 non-null  int64
 23  CustomerType                 33968 non-null  object
 24  ADR                          33968 non-null  float64
 25  RequiredCarParkingSpaces     33968 non-null  int64
 26  TotalOfSpecialRequests       33968 non-null  int64
 27  ReservationStatus            33968 non-null  object
 28  ReservationStatusDate        33968 non-null  object
 29  Total Guest                  33968 non-null  int64
 30  HasChildren                  33968 non-null  int64
 31  HasBabies                    33968 non-null  int64
 32  Total Stay Duration          33968 non-null  int64
 33  Revenue                      33968 non-null  float64
 34  TotalPreviousBookings        33968 non-null  int64
 35  CancellationRate             33968 non-null  float64
 36  BookingChangeRate            33968 non-null  float64
dtypes: float64(4), int64(22), object(11)
memory usage: 9.8+ MB

### Treating outlier

In [25]:
def detect_outliers_iqr(df):
    outlier_indices=[]

    for col in df.select_dtypes(include=np.number).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        outliers = df[(df[col] < lower) | (df[col] > upper)].index
        outlier_indices.extend(outliers)
    return list(set(outlier_indices))


outliers = detect_outliers_iqr(df)
print("Total outliers detected:", len(outliers))

Total outliers detected: 23863

In [26]:
df.head()

,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,ReservationStatus,ReservationStatusDate,Total Guest,HasChildren,HasBabies,Total Stay Duration,Revenue,TotalPreviousBookings,CancellationRate,BookingChangeRate
0,0,342,2015,July,27,1,0,0,2,0,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.008746
1,0,737,2015,July,27,1,0,0,2,0,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.005420
2,0,7,2015,July,27,1,0,1,1,0,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
3,0,13,2015,July,27,1,0,1,1,0,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
4,0,14,2015,July,27,1,0,2,2,0,...,Check-Out,2015-07-03,2,0,0,2,196.0,0,0.0,0.000000

In [27]:
outliers

[0,
 1,
 2,
 3,
 8,
 9,
 10,
 12,
 13,
 15,
 20,
 21,
 23,
 25,
 27,
 29,
 30,
 31,
 32,
 34,
 35,
 37,
 38,
 40,
 45,
 48,
 49,
 52,
 53,
 54,
 55,
 61,
 64,
 65,
 68,
 69,
 70,
 71,
 74,
 75,
 76,
 77,
 78,
 79,
 81,
 82,
 83,
 85,
 86,
 87,
 89,
 94,
 95,
 96,
 97,
 98,
 101,
 102,
 103,
 105,
 106,
 107,
 109,
 111,
 113,
 114,
 118,
 119,
 121,
 122,
 123,
 124,
 125,
 127,
 132,
 133,
 134,
 135,
 137,
 140,
 141,
 143,
 148,
 149,
 150,
 152,
 154,
 155,
 156,
 158,
 159,
 160,
 162,
 163,
 164,
 165,
 166,
 168,
 169,
 171,
 173,
 175,
 177,
 178,
 179,
 180,
 181,
 184,
 186,
 187,
 189,
 190,
 193,
 194,
 195,
 198,
 199,
 201,
 203,
 204,
 205,
 206,
 208,
 209,
 211,
 212,
 213,
 216,
 217,
 218,
 220,
 221,
 222,
 223,
 225,
 227,
 228,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 245,
 247,
 254,
 255,
 262,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 276,
 278,
 280,
 282,
 283,
 284,
 285,
 287,
 290,
 291,
 292,
 295,
 300,
 302,
 303,
 304,
 306,
 307,
 308,
 309,
 310,
 314,
 315,
 317,
 320,
 322,
 323,
 324,
 327,
 328,
 331,
 336,
 337,
 338,
 340,
 341,
 343,
 344,
 345,
 347,
 348,
 350,
 352,
 354,
 355,
 357,
 358,
 359,
 360,
 362,
 363,
 364,
 365,
 367,
 369,
 371,
 373,
 374,
 375,
 376,
 380,
 381,
 382,
 383,
 386,
 387,
 388,
 389,
 390,
 392,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 404,
 405,
 406,
 407,
 408,
 409,
 411,
 412,
 418,
 420,
 421,
 423,
 424,
 428,
 434,
 437,
 438,
 439,
 440,
 441,
 442,
 444,
 445,
 446,
 447,
 450,
 451,
 453,
 455,
 457,
 458,
 464,
 465,
 466,
 467,
 472,
 473,
 475,
 477,
 479,
 481,
 482,
 484,
 485,
 486,
 487,
 492,
 493,
 494,
 495,
 496,
 497,
 501,
 504,
 505,
 506,
 507,
 510,
 511,
 513,
 514,
 515,
 516,
 517,
 518,
 521,
 523,
 524,
 525,
 526,
 527,
 528,
 530,
 535,
 537,
 539,
 542,
 543,
 544,
 546,
 548,
 549,
 550,
 551,
 554,
 555,
 557,
 558,
 559,
 562,
 564,
 565,
 566,
 567,
 568,
 570,
 572,
 573,
 574,
 577,
 579,
 580,
 582,
 584,
 585,
 586,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 597,
 599,
 600,
 601,
 602,
 604,
 605,
 607,
 609,
 611,
 612,
 613,
 614,
 615,
 617,
 618,
 619,
 620,
 622,
 623,
 624,
 625,
 627,
 628,
 629,
 630,
 631,
 632,
 635,
 641,
 644,
 645,
 646,
 649,
 650,
 651,
 652,
 656,
 657,
 658,
 659,
 661,
 663,
 664,
 665,
 670,
 672,
 673,
 674,
 677,
 679,
 680,
 681,
 682,
 683,
 685,
 687,
 688,
 689,
 690,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 702,
 704,
 705,
 706,
 707,
 708,
 710,
 711,
 712,
 713,
 716,
 719,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 731,
 732,
 733,
 737,
 738,
 740,
 742,
 743,
 744,
 746,
 747,
 748,
 750,
 751,
 752,
 754,
 755,
 756,
 760,
 761,
 762,
 763,
 764,
 769,
 772,
 773,
 775,
 776,
 777,
 779,
 780,
 782,
 786,
 787,
 789,
 790,
 792,
 793,
 794,
 795,
 796,
 797,
 799,
 800,
 801,
 802,
 803,
 804,
 807,
 808,
 809,
 810,
 813,
 814,
 815,
 816,
 817,
 818,
 820,
 821,
 823,
 824,
 825,
 826,
 827,
 828,
 830,
 831,
 832,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 843,
 845,
 846,
 847,
 849,
 850,
 852,
 853,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 874,
 875,
 878,
 881,
 882,
 884,
 885,
 886,
 887,
 889,
 890,
 891,
 892,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 906,
 907,
 909,
 912,
 913,
 914,
 916,
 917,
 918,
 919,
 920,
 921,
 923,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 933,
 936,
 937,
 938,
 940,
 941,
 943,
 945,
 946,
 949,
 950,
 951,
 952,
 955,
 956,
 957,
 958,
 960,
 961,
 962,
 964,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 977,
 978,
 981,
 982,
 983,
 987,
 988,
 989,
 992,
 993,
 995,
 996,
 997,
 998,
 1001,
 1003,
 1005,
 1006,
 1008,
 1009,
 1011,
 1013,
 1015,
 1017,
 1018,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1028,
 1031,
 1032,
 1033,
 1034,
 1036,
 1037,
 1038,
 1040,
 1041,
 1042,
 1044,
 1046,
 1047,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1063,
 1064,
 1066,
 1067,
 1068,
 1072,
 1074,
 1075,
 1076,
 1077,
 1078,
 1080,
 1081,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1094,
 1095,
 1099,
 1101,
 1102,
 1104,
 1105,
 1106,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1116,
 1119,
 1120,
 1122,
 1123,
 1124,
 1125,
 1126,
 1129,
 1130,
 1132,
 1133,
 1134,
 1135,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1155,
 1162,
 1163,
 1164,
 1165,
 1166,
 1168,
 1169,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1179,
 1180,
 1181,
 1182,
 1183,
 1185,
 1186,
 1187,
 1190,
 1191,
 1194,
 1195,
 1196,
 1197,
 1198,
 1200,
 1202,
 1203,
 1204,
 1205,
 1206,
 1209,
 1210,
 1211,
 1212,
 1214,
 1215,
 1216,
 1217,
 1218,
 1219,
 1220,
 1221,
 1222,
 1223,
 1224,
 1225,
 1228,
 1229,
 1231,
 1233,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1245,
 1246,
 1247,
 1250,
 1251,
 1253,
 1255,
 1257,
 1258,
 1259,
 1260,
 1261,
 1263,
 1264,
 1266,
 1267,
 1268,
 1270,
 1271,
 1273,
 1276,
 1277,
 1278,
 1280,
 1281,
 1283,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1294,
 1295,
 1297,
 1298,
 1299,
 1300,
 1302,
 1303,
 1304,
 1305,
 1306,
 1308,
 1309,
 1311,
 1312,
 1313,
 1315,
 1316,
 1317,
 1318,
 1320,
 1322,
 1323,
 1324,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 1337,
 1339,
 1340,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1350,
 1351,
 1352,
 1353,
 1355,
 1357,
 1359,
 1360,
 1362,
 1363,
 1364,
 1366,
 1367,
 1368,
 1369,
 1370,
 1371,
 1372,
 1373,
 1375,
 1376,
 1377,
 1380,
 1382,
 1383,
 1385,
 1386,
 1387,
 1388,
 1390,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1400,
 1401,
 1402,
 1405,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1414,
 1415,
 1416,
 1418,
 1424,
 1426,
 1427,
 1428,
 1430,
 1431,
 1434,
 1435,
 1436,
 1437,
 1438,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1449,
 1454,
 1456,
 1457,
 1458,
 1459,
 1460,
 1462,
 1463,
 1465,
 1467,
 1470,
 1472,
 1473,
 1475,
 1476,
 1479,
 1480,
 1481,
 1484,
 1485,
 1486,
 1489,
 1490,
 1491,
 1492,
 1493,
 1495,
 1496,
 1497,
 1498,
 1500,
 1501,
 1503,
 1505,
 1506,
 1507,
 1508,
 1510,
 1511,
 1512,
 1513,
 1514,
 1516,
 1517,
 1518,
 1519,
 1524,
 1525,
 1526,
 ...]