# Exploratory Data Analysis (EDA)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

df = pd.read_csv(r"Data/H1_cleaned_feature_engineering.csv")

In [4]:
df.head()

,Unnamed: 0,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateMonth,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,...,ReservationStatus,ReservationStatusDate,Total Guest,HasChildren,HasBabies,Total Stay Duration,Revenue,TotalPreviousBookings,CancellationRate,BookingChangeRate
0,0,0,342,2015,July,27,1,0,0,2,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.008746
1,1,0,737,2015,July,27,1,0,0,2,...,Check-Out,2015-07-01,2,0,0,0,0.0,0,0.0,0.005420
2,2,0,7,2015,July,27,1,0,1,1,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
3,3,0,13,2015,July,27,1,0,1,1,...,Check-Out,2015-07-02,1,0,0,1,75.0,0,0.0,0.000000
4,4,0,14,2015,July,27,1,0,2,2,...,Check-Out,2015-07-03,2,0,0,2,196.0,0,0.0,0.000000

## Dataset Overview

In [6]:
df.shape

(33967, 38)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33967 entries, 0 to 33966
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   33967 non-null  int64
 1   IsCanceled                   33967 non-null  int64
 2   LeadTime                     33967 non-null  int64
 3   ArrivalDateYear              33967 non-null  int64
 4   ArrivalDateMonth             33967 non-null  object
 5   ArrivalDateWeekNumber        33967 non-null  int64
 6   ArrivalDateDayOfMonth        33967 non-null  int64
 7   StaysInWeekendNights         33967 non-null  int64
 8   StaysInWeekNights            33967 non-null  int64
 9   Adults                       33967 non-null  int64
 10  Children                     33967 non-null  int64
 11  Babies                       33967 non-null  int64
 12  Meal                         33967 non-null  object
 13  Country                      33967 non-null  object
 14  MarketSegment                33967 non-null  object
 15  DistributionChannel          33967 non-null  object
 16  IsRepeatedGuest              33967 non-null  int64
 17  PreviousCancellations        33967 non-null  int64
 18  PreviousBookingsNotCanceled  33967 non-null  int64
 19  ReservedRoomType             33967 non-null  object
 20  AssignedRoomType             33967 non-null  object
 21  BookingChanges               33967 non-null  int64
 22  DepositType                  33967 non-null  object
 23  DaysInWaitingList            33967 non-null  int64
 24  CustomerType                 33967 non-null  object
 25  ADR                          33967 non-null  float64
 26  RequiredCarParkingSpaces     33967 non-null  int64
 27  TotalOfSpecialRequests       33967 non-null  int64
 28  ReservationStatus            33967 non-null  object
 29  ReservationStatusDate        33967 non-null  object
 30  Total Guest                  33967 non-null  int64
 31  HasChildren                  33967 non-null  int64
 32  HasBabies                    33967 non-null  int64
 33  Total Stay Duration          33967 non-null  int64
 34  Revenue                      33967 non-null  float64
 35  TotalPreviousBookings        33967 non-null  int64
 36  CancellationRate             33967 non-null  float64
 37  BookingChangeRate            33967 non-null  float64
dtypes: float64(4), int64(23), object(11)
memory usage: 9.8+ MB

In [8]:
df.describe()

,Unnamed: 0,IsCanceled,LeadTime,ArrivalDateYear,ArrivalDateWeekNumber,ArrivalDateDayOfMonth,StaysInWeekendNights,StaysInWeekNights,Adults,Children,...,RequiredCarParkingSpaces,TotalOfSpecialRequests,Total Guest,HasChildren,HasBabies,Total Stay Duration,Revenue,TotalPreviousBookings,CancellationRate,BookingChangeRate
count,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,...,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000,33967.000000
mean,20840.091766,0.234816,83.368652,2016.141579,27.154562,15.910825,1.214532,3.177319,1.874937,0.149321,...,0.160685,0.679041,2.040569,0.100892,0.016045,4.391851,461.827702,0.194130,0.005804,0.034279
std,11505.092027,0.423890,91.799632,0.720943,13.806490,8.886927,1.163890,2.496226,0.737508,0.476456,...,0.373919,0.829072,0.918836,0.301190,0.125650,3.439831,477.243102,1.186068,0.052433,0.193163
min,0.000000,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11399.500000,0.000000,8.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,...,0.000000,0.000000,2.000000,0.000000,0.000000,2.000000,118.000000,0.000000,0.000000,0.000000
50%,21352.000000,0.000000,47.000000,2016.000000,28.000000,16.000000,1.000000,3.000000,2.000000,0.000000,...,0.000000,0.000000,2.000000,0.000000,0.000000,4.000000,300.000000,0.000000,0.000000,0.000000
75%,30584.500000,0.000000,138.000000,2017.000000,37.000000,24.000000,2.000000,5.000000,2.000000,0.000000,...,0.000000,1.000000,2.000000,0.000000,0.000000,7.000000,644.980000,0.000000,0.000000,0.000000
max,40059.000000,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,...,8.000000,5.000000,55.000000,1.000000,1.000000,69.000000,7590.000000,31.000000,0.962963,6.000000